apiVersion: v1
kind: Namespace
metadata:
  name: hope

---
apiVersion: v1
kind: Secret
metadata:
  name: hope-db-secret
  namespace: hope
type: Opaque
stringData:  # We dont need to worry about converting to base64
  POSTGRES_USER: hope
  POSTGRES_PASSWORD: hope-database-pass
  POSTGRES_DB: hopev2

---
apiVersion: v1
kind: PersistentVolume                        # Create a PV
metadata:
  name: hope-postgres-pv
  namespace: hope
  labels:
    app: hope-db
spec:
  storageClassName: manual                    # Storage class. A PV Claim requesting the same storageClass can be bound to this volume.
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:                                   # hostPath PersistentVolume is used for development and testing. It uses a file/directory on the Node to emulate network-attached storage
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain       # Retain the PV even after PVC is deleted.

---
apiVersion: v1
kind: PersistentVolumeClaim                   # Create a PersistentVolumeClaim to request a PersistentVolume storage
metadata:                                     # Claim name and labels
  name: hope-postgres-pvc
  namespace: hope
  labels:
    app: hope-db
spec:                                         # Access mode and resource limits
  storageClassName: manual                    # Request a certain storage class
  accessModes:
    - ReadWriteMany                           # ReadWriteMany means the volume can be mounted as read-write by many Nodes
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment                                 # Type of the kubernetes resource
metadata:
  name: hope-db                                  # Name of the deployment
  namespace: hope
  labels:                                        # Labels applied to this deployment 
    app: hope-db
spec:
  selector:
    matchLabels:                                  # This deployment applies to the Pods matching the specified labels
      app: hope-db
      tier: postgres
  replicas: 1
  template:                                       # Template for the Pods in this deployment
    metadata:
      namespace: hope
      labels:                                     # Labels to be applied to the Pods in this deployment
        app: hope-db
        tier: postgres
    spec:                                         # The spec for the containers that will be run inside the Pods in this deployment
      containers:
        - image: postgres:latest                  # The container image
          name: postgres
          imagePullPolicy: "IfNotPresent"
          envFrom:                                # Get the environmental variables from a secret file whose name is "postgres-secret" 
            - secretRef:
                name: hope-db-secret
          ports:
            - containerPort: 5432                   # The port that the container exposes 
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage     # This name should match the name specified in `volumes.name`
      volumes:                                      # A PersistentVolume is mounted as a volume to the Pod 
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: hope-postgres-pvc

---
apiVersion: v1                                      # API version
kind: Service                                       # Type of kubernetes resource 
metadata:
  name: hope-db-service                          # Name of the resource
  namespace: hope
  labels:                                           # Labels that will be applied to the resource
    app: hope-db
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:                                         # Selects any Pod with labels `app=fullstack-postgres,tier=postgres`
    app: hope-db
    tier: postgres
