BEGIN;

INSERT INTO "selfcare".self_healing_audios(id, theme_id, mood_id, title, description, image_url, audio_url, benefit, script_writer, voice_over, duration, "order") VALUES
    (1, 1, 2, 'Mengenal Rasa Bersyukur', 'Menghadirkan rasa syukur dalam kehidupan', 'https://images.unsplash.com/photo-1489797715492-dbd3bd61c6b5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://dearhope.s3.ap-southeast-3.amazonaws.com/audio/Audio+Self+Healing+1+-+Rasa+Bersyukur.mp3', 'Menghadirkan Bersyukur', 'Shania Amalia Hafta', 'Shania Amalia Hafta', 678, 1),
    (2, 2, 2, 'Aku bersyukur, karena...', 'Mengenalkan apa itu arti bersyukur', 'https://images.unsplash.com/photo-1489797715492-dbd3bd61c6b5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://dearhope.s3.ap-southeast-3.amazonaws.com/audio/Audio+Self+Healing+2+-+Aku+Bersyukur%2C+karena.mp3', 'Mengenalkan rasa bersyukur dalam kehidupan', 'Shania Amalia Hafta', 'Shania Amalia Hafta', 700, 1),
    (3, 1, 2, 'Deadline pekerjaan', 'Menenangkan diri saat berhadapan dengan deadline pekerjaan', 'https://images.unsplash.com/photo-1489797715492-dbd3bd61c6b5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://dearhope.s3.ap-southeast-3.amazonaws.com/audio/Audio+Self+Healing+3+-+Deadline+Pekerjaan.mp3', 'Menenangkan diri pada saat berhadapan dengan deadline pekerjaan', 'Shania Amalia Hafta', 'Shania Amalia Hafta', 462, 2),
    (4, 2, 2, 'Arti keberhasilan', 'Mencari makna kata berhasil', 'https://images.unsplash.com/photo-1489797715492-dbd3bd61c6b5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://dearhope.s3.ap-southeast-3.amazonaws.com/audio/Audio+Self+Healing+4+-+Arti+Keberhasilan.mp3', 'Mencari makna kata berhasil', 'Shania Amalia Hafta', 'Shania Amalia Hafta', 505, 2),
    (5, 1, 1, 'Diri yang krisis', 'Mengenal diri lebih dalam', 'https://images.unsplash.com/photo-1489797715492-dbd3bd61c6b5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://dearhope.s3.ap-southeast-3.amazonaws.com/audio/Audio+Self+Healing+5+-+Krisis+Diri.mp3', 'Mengenal diri lebih dalam', 'Shania Amalia Hafta', 'Shania Amalia Hafta', 566, 3);

COMMIT;