name: Deploy

on:
  # push:
  #   branches: [ "main" ]
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches: [main]

jobs:

  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: SSH to EC2 and Run Docker
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        USERNAME: ${{ secrets.SSH_USER }}
        HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
        IMAGE: ${{ secrets.AWS_ECR_IMAGE }}
        DB_HOST: ${{ secrets.AWS_DATABASE_HOST }}

      run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            docker pull $IMAGE && 
            docker stop dearhope && 
            docker run -d -e DBCONFIG_HOST=$DB_HOST -p 8000:8000 --name dearhope $IMAGE &&
            docker ps
          '